#项目运行端口
server:
  port: 8084

spring:
  #DataSource配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mo54?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: ''
  jpa:
    database: mysql
    # Show or not log for each sql query
    show-sql: true
    generate-ddl: false
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        # stripped before adding them to the entity manager
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect